//! `accretion` — a Polis city generated by literally growing the town, one
//! file at a time, in git commit order (PRD §7.1, §7.2).

mod accrete;
mod city;
mod geom;
mod graph;
mod metrics;
mod raster;
mod render;
mod repo;
mod synth;
mod voronoi;

use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::time::Instant;

use polis_layout::determinism::{fnv1a64, quantize_f64};

use accrete::{FileRec, Params, Settlement};
use city::City;
use geom::P;
use graph::Graph;
use metrics::Metrics;
use repo::RepoData;

const WELD_TOL: f64 = 0.004;

/// Sweep knobs. Every one has a compiled-in default; the environment override
/// exists only so the tuning sweep does not need a rebuild per trial.
pub fn env_f(name: &str, default: f64) -> f64 {
    std::env::var(name)
        .ok()
        .and_then(|v| v.parse().ok())
        .unwrap_or(default)
}
pub fn env_u(name: &str, default: u32) -> u32 {
    std::env::var(name)
        .ok()
        .and_then(|v| v.parse().ok())
        .unwrap_or(default)
}

pub struct Built {
    pub s: Settlement,
    pub cells: voronoi::Cells,
    pub g: Graph,
    pub city: City,
    pub sep: f64,
}

fn tuned_params(n: usize) -> Params {
    let mut p = Params::default();
    // Small repositories need finer ground to make a town at all; large ones
    // need coarser ground to stay inside the frame budget.
    if n < 400 {
        p.cap_core = env_u("CAP_CORE", 1);
        p.cap_rim = env_u("CAP_RIM", 2);
    } else if n < 2000 {
        p.cap_core = env_u("CAP_CORE", 2);
        p.cap_rim = env_u("CAP_RIM", 4);
    } else {
        p.cap_core = env_u("CAP_CORE", 3);
        p.cap_rim = env_u("CAP_RIM", 6);
    }
    p.sep_core = env_f("SEP_CORE", p.sep_core);
    p.sep_rim = env_f("SEP_RIM", p.sep_rim);
    p
}

pub fn grow(mut files: Vec<FileRec>, params: Params) -> Settlement {
    // Commit order, ties by path: the growth order is a property of the
    // repository, never of the order the files were handed to us.
    files.sort_by(|a, b| {
        (a.growth_index, a.path.as_str()).cmp(&(b.growth_index, b.path.as_str()))
    });
    let n = u32::try_from(files.len()).unwrap_or(u32::MAX);
    let mut s = Settlement::new(params, n);
    for f in files {
        s.add_file(f);
    }
    s
}

/// Roads, blocks, lots, buildings — in that order, from the settled ground.
pub fn finish(s: Settlement, cells: voronoi::Cells, imports: &[(u32, u32)]) -> Built {
    let sep = s.params.sep_rim;
    let mut g = Graph::from_cells(&cells.cells, WELD_TOL);

    // The organic signature: contract near-coincident junctions so three-way
    // corners fuse into four- and five-way ones (PRD §7.2).
    g.collapse_short(s.params.sep_core * env_f("LMIN", 1.15));
    g.compact_nodes();
    g.curve_roads(s.params.terrain_seed ^ 0x51, 0.10, env_f("BEND", 0.075));

    // Prune a minority of interior boundaries so plots merge into larger,
    // irregular blocks and long through-roads appear.
    let faces1 = g.faces();
    let (lo, hi) = s.extent();
    let centre = [(lo[0] + hi[0]) * 0.5, (lo[1] + hi[1]) * 0.5];
    let radius = geom::dist(lo, hi) * 0.5;
    let doomed = graph::choose_prunes(&g, &faces1, centre, radius, s.params.terrain_seed ^ 0xA7);
    g.delete_edges(&doomed);
    g.compact_nodes();
    g.curve_roads(s.params.terrain_seed ^ 0x51, 0.10, env_f("BEND", 0.075));

    let faces = g.faces();
    graph::classify_roads(&mut g, 26);
    let city = city::assemble(&s, &g, faces, imports, sep);
    Built {
        s,
        cells,
        g,
        city,
        sep,
    }
}

pub fn build_all(data: RepoData) -> Built {
    let params = tuned_params(data.files.len());
    let s = grow(data.files, params);
    let pos = s.plot_positions();
    let cells = voronoi::build(&pos, s.params.sep_rim, s.params.terrain_seed ^ 0x9F);
    finish(s, cells, &data.imports)
}

/// A canonical, byte-exact serialisation of the whole layout. Two processes
/// producing the same bytes is the determinism proof (PRD §7.4).
pub fn digest(b: &Built) -> String {
    let mut o = String::with_capacity(1 << 20);
    let q = |v: f64| -> f64 { quantize_f64(v) };
    let _ = writeln!(o, "V {}", b.g.nodes.len());
    for n in &b.g.nodes {
        let _ = writeln!(o, "n {:.4} {:.4}", q(n[0]), q(n[1]));
    }
    let _ = writeln!(o, "E {}", b.g.edges.len());
    for (i, e) in b.g.edges.iter().enumerate() {
        let _ = write!(o, "e {} {} {:?}", e.0, e.1, b.g.class[i]);
        for p in &b.g.curve[i] {
            let _ = write!(o, " {:.4},{:.4}", q(p[0]), q(p[1]));
        }
        o.push('\n');
    }
    let _ = writeln!(o, "B {}", b.city.blocks.len());
    for bl in &b.city.blocks {
        let _ = write!(o, "b {:?} {}", bl.district, bl.open);
        for p in &bl.ring {
            let _ = write!(o, " {:.4},{:.4}", q(p[0]), q(p[1]));
        }
        o.push('\n');
    }
    let _ = writeln!(o, "L {}", b.city.lots.len());
    for l in &b.city.lots {
        let _ = write!(o, "l {} {:?}", l.block, l.files);
        for p in &l.ring {
            let _ = write!(o, " {:.4},{:.4}", q(p[0]), q(p[1]));
        }
        o.push('\n');
    }
    let _ = writeln!(o, "H {}", b.city.buildings.len());
    for bu in &b.city.buildings {
        let _ = write!(
            o,
            "h {} {}",
            b.s.files[bu.file as usize].path.as_str(),
            bu.lot
        );
        for p in &bu.ring {
            let _ = write!(o, " {:.4},{:.4}", q(p[0]), q(p[1]));
        }
        o.push('\n');
    }
    let _ = writeln!(o, "S {}", b.city.streets.len());
    for st in &b.city.streets {
        let _ = write!(o, "s {}", st.weight);
        for p in &st.polyline {
            let _ = write!(o, " {:.4},{:.4}", q(p[0]), q(p[1]));
        }
        o.push('\n');
    }
    let _ = writeln!(o, "P {}", b.s.plots.len());
    for pl in &b.s.plots {
        let _ = writeln!(
            o,
            "p {:.4} {:.4} {} {}",
            q(pl.pos[0]),
            q(pl.pos[1]),
            pl.district,
            pl.files.len()
        );
    }
    o
}

/// Grow the town, then add the last `k` files one at a time, measuring what a
/// single growth step actually costs and how much ground moves.
fn incremental_probe(data: &RepoData, k: usize, m: &mut Metrics) -> String {
    let params = tuned_params(data.files.len());
    let mut files = data.files.clone();
    files.sort_by(|a, b| {
        (a.growth_index, a.path.as_str()).cmp(&(b.growth_index, b.path.as_str()))
    });
    let tail: Vec<FileRec> = files.split_off(files.len().saturating_sub(k));

    let mut s = Settlement::new(params, u32::try_from(data.files.len()).unwrap_or(u32::MAX));
    for f in files {
        s.add_file(f);
    }
    let pos = s.plot_positions();
    let mut cells = voronoi::build(&pos, s.params.sep_rim, s.params.terrain_seed ^ 0x9F);
    let sep = s.params.sep_rim;

    let mut local_ms: Vec<f64> = Vec::new();
    let mut full_ms: Vec<f64> = Vec::new();
    let mut moved: Vec<f64> = Vec::new();
    let mut new_plots = 0usize;

    let mut prev_nodes: Vec<(i64, i64)> = {
        let g = Graph::from_cells(&cells.cells, WELD_TOL);
        g.nodes
            .iter()
            .map(|n| ((n[0] * 1000.0) as i64, (n[1] * 1000.0) as i64))
            .collect()
    };
    prev_nodes.sort_unstable();

    for f in tail {
        let before = s.plots.len();
        let t0 = Instant::now();
        s.add_file(f);
        let mut which: Vec<usize> = Vec::new();
        if s.plots.len() > before {
            new_plots += 1;
            let at = s.plots[before].pos;
            let pos = s.plot_positions();
            let mut moved_sites = vec![at];
            moved_sites.extend(voronoi::update_phantoms(&mut cells, &pos, at, sep));
            which = voronoi::affected(&pos, &moved_sites, sep);
            voronoi::rebuild_subset(&pos, sep, &mut cells, &which);
        }
        let t_local = t0.elapsed().as_secs_f64() * 1000.0;

        let t1 = Instant::now();
        let g = Graph::from_cells(&cells.cells, WELD_TOL);
        let mut g2 = g;
        g2.collapse_short(s.params.sep_core * 0.34);
        g2.compact_nodes();
        g2.curve_roads(s.params.terrain_seed ^ 0x51, 0.10, 0.075);
        let _ = g2.faces();
        let t_full = t_local + t1.elapsed().as_secs_f64() * 1000.0;

        let mut now: Vec<(i64, i64)> = g2
            .nodes
            .iter()
            .map(|n| ((n[0] * 1000.0) as i64, (n[1] * 1000.0) as i64))
            .collect();
        now.sort_unstable();
        let mut i = 0;
        let mut j = 0;
        let mut diff = 0usize;
        while i < prev_nodes.len() && j < now.len() {
            match prev_nodes[i].cmp(&now[j]) {
                std::cmp::Ordering::Equal => {
                    i += 1;
                    j += 1;
                }
                std::cmp::Ordering::Less => {
                    i += 1;
                    diff += 1;
                }
                std::cmp::Ordering::Greater => {
                    j += 1;
                    diff += 1;
                }
            }
        }
        diff += (prev_nodes.len() - i) + (now.len() - j);
        prev_nodes = now;

        local_ms.push(t_local);
        full_ms.push(t_full);
        moved.push(diff as f64);
        if which.len() > 200 {
            // Should never happen; the affected set is a local neighbourhood.
            eprintln!("WARN: affected set {} cells", which.len());
        }
    }

    let med = |mut v: Vec<f64>| -> (f64, f64) {
        if v.is_empty() {
            return (0.0, 0.0);
        }
        v.sort_by(|a, b| a.partial_cmp(b).unwrap());
        (v[v.len() / 2], v[(v.len() * 95 / 100).min(v.len() - 1)])
    };
    let (lm, lp) = med(local_ms.clone());
    let (fm, fp) = med(full_ms.clone());
    let (mm, _) = med(moved.clone());
    m.incr_ms_median = fm;
    m.incr_ms_p95 = fp;
    m.incr_moved_nodes_median = mm;
    format!(
        "INCREMENTAL {k} single-file adds ({new_plots} needed new ground):\n  \
         local growth step (settle + local cells + local phantoms): median {lm:.3} ms, p95 {lp:.3} ms\n  \
         prototype's full downstream rebuild on top of it:          median {fm:.3} ms, p95 {fp:.3} ms\n  \
         road nodes whose position changed, median per add:         {mm:.1} of {}\n",
        prev_nodes.len()
    )
}

fn out_dir() -> PathBuf {
    PathBuf::from("C:/coding/agentolis/docs/design/accretion")
}

fn render_set(b: &Built, m: &Metrics, tag: &str, title: &str, px: usize) -> Vec<PathBuf> {
    let dir = out_dir();
    std::fs::create_dir_all(&dir).expect("out dir");
    let mut paths = Vec::new();
    let c = render::render_city(&b.s, &b.g, &b.city, m, title, px, 2);
    let p1 = dir.join(format!("{tag}.png"));
    c.write_png(&p1).expect("png");
    paths.push(p1);
    if tag == "small" {
        let j = render::render_junctions(&b.g, m, "ROAD GRAPH ONLY - JUNCTIONS BY DEGREE", px, 2);
        let p2 = dir.join("junctions.png");
        j.write_png(&p2).expect("png");
        paths.push(p2);
    }
    if tag == "large" {
        let j = render::render_junctions(
            &b.g,
            m,
            "ROAD GRAPH ONLY - JUNCTIONS BY DEGREE - 5000 FILES",
            px,
            2,
        );
        let p2 = dir.join("junctions-large.png");
        j.write_png(&p2).expect("png");
        paths.push(p2);
    }
    paths
}

fn run(tag: &str, data: RepoData, title: &str, px: usize, incr: usize) -> String {
    let n = data.files.len();
    let t = Instant::now();
    let b = build_all(RepoData {
        files: data.files.clone(),
        imports: data.imports.clone(),
    });
    let gen_ms = t.elapsed().as_secs_f64() * 1000.0;
    let mut m = metrics::measure(&b.s, &b.g, &b.city, b.sep);
    m.gen_ms = gen_ms;
    let incr_report = if incr > 0 {
        incremental_probe(&data, incr, &mut m)
    } else {
        String::new()
    };
    let paths = render_set(&b, &m, tag, title, px);
    let d = digest(&b);
    let h = fnv1a64(d.as_bytes());
    std::fs::write(out_dir().join(format!("{tag}.layout.txt")), &d).expect("digest");
    let mut o = m.report(title);
    o.push_str(&incr_report);
    let _ = writeln!(o, "PLOTS       {} settled for {} files", b.s.plots.len(), n);
    let _ = writeln!(o, "DIGEST      fnv1a64 = {h:016x}  ({} bytes)", d.len());
    for p in paths {
        let _ = writeln!(o, "RENDER      {}", p.display());
    }
    o
}

fn main() {
    let args: Vec<String> = std::env::args().collect();
    let cmd = args.get(1).map(String::as_str).unwrap_or("all");
    match cmd {
        "small" | "all" => {
            let data = repo::read(Path::new("C:/coding/agentolis"));
            eprintln!("agentolis: {} files", data.files.len());
            print!(
                "{}",
                run(
                    "small",
                    data,
                    "POLIS / ACCRETION - AGENTOLIS REPOSITORY",
                    1600,
                    24
                )
            );
            if cmd == "all" {
                let d = synth::generate(5000, 0xACCE_7107_0000_0001);
                eprintln!("synthetic: {} files", d.files.len());
                print!(
                    "{}",
                    run(
                        "large",
                        d,
                        "POLIS / ACCRETION - SYNTHETIC 5000-FILE REPOSITORY",
                        1600,
                        24
                    )
                );
            }
        }
        "large" => {
            let d = synth::generate(5000, 0xACCE_7107_0000_0001);
            print!(
                "{}",
                run(
                    "large",
                    d,
                    "POLIS / ACCRETION - SYNTHETIC 5000-FILE REPOSITORY",
                    1600,
                    24
                )
            );
        }
        // Determinism: print only the digests, for a cross-process diff.
        "hash" => {
            let a = build_all(repo::read(Path::new("C:/coding/agentolis")));
            let da = digest(&a);
            println!("small {:016x} {}", fnv1a64(da.as_bytes()), da.len());
            let b = build_all(synth::generate(5000, 0xACCE_7107_0000_0001));
            let db = digest(&b);
            println!("large {:016x} {}", fnv1a64(db.as_bytes()), db.len());
            if let Some(p) = args.get(2) {
                std::fs::write(format!("{p}.small.txt"), da).unwrap();
                std::fs::write(format!("{p}.large.txt"), db).unwrap();
            }
        }
        // Determinism under a shuffled input ordering.
        "shuffle" => {
            let mut d = repo::read(Path::new("C:/coding/agentolis"));
            let n = d.files.len();
            let mut out: Vec<FileRec> = Vec::with_capacity(n);
            let mut i = 0usize;
            while out.len() < n {
                out.push(d.files[i % n].clone());
                i = (i * 7 + 13) % n.max(1);
                if out.len() > n {
                    break;
                }
            }
            // A deterministic derangement: reverse then rotate.
            d.files.reverse();
            d.files.rotate_left(n / 3);
            let b = build_all(d);
            let db = digest(&b);
            println!("shuffled-small {:016x} {}", fnv1a64(db.as_bytes()), db.len());
        }
        other => eprintln!("unknown command {other}"),
    }
}

#[allow(dead_code)]
fn unused(_: &City, _: P) {}
